# @package _global_

# to execute this experiment run:
# python train.py experiment=example

defaults:
  - /datamodule: ncrna
  - /callbacks: lm
  - /trainer: ddp_bf16

# all parameters below will be merged with parameters from default configurations set above
# this allows you to overwrite only specified parameters

# name of the run determines folder name in logs
project: "evoflow_150m"
name: "default-mini-320k" # default-giga-1m

datamodule:
  max_tokens: 40000
  max_len: 1022
  mini_run: false

model:
  _target_: rnadiff
  num_diffusion_timesteps: 500
  gradient_ckpt: false
  rdm_couple: false
  lora: # TODO: Implement
    lora: false
    lora_rank: 16
    lora_dropout: 0.1
    lora_target_module: None
    modules_to_save: None
  net:
    arch_type: lm

task:
  _target_: lm/pretrained
  learning:
    noise: random_mask # enable cmlm training with uniform random masking
    watch_t1_t2_loss: false
    cal_constant_loss: false
    weight: linear
  criterion:
    _target_: src.ncrna.modules.cross_entropy.RDMCrossEntropyLoss
    label_smoothing: 0.0
    ignore_index: 1
  optimizer:
    type: adamw
    _partial_: true
    lr: ${train.lr}
    betas: 
      - 0.9
      - 0.98
    weight_decay: 0.01 # 0.0001
  lr_scheduler:
    type: polynomial
    warmup_steps: 2000
    total_steps: ${trainer.max_steps}
    lr: ${train.lr}
    lr_end: 1e-5
    warmup_init_lr: 1e-07
    power: 1

train:
  seed: 42
  lr: 0.00004
  monitor: "val/loss"
  mode: "min"
  patience: 1000

trainer:
  min_epochs: 10
  max_epochs: 10000
  gradient_clip_val: 0.0
  # val_check_interval: 10
  num_sanity_val_steps: 0
  reload_dataloaders_every_n_epochs: 1
  use_distributed_sampler: false
  max_steps: 500_000
  accumulate_grad_batches: 1
  check_val_every_n_epoch: null
  val_check_interval: 20000
  enable_progress_bar: true
  num_nodes: 1